### ISSUE TITLE
VR-WORLD: Set up Kanban

### ISSUE THREAD

**Issue by rica213** [rica213/vr-world#24]
Hi, 

We are four people team. 
👉🏽 Larissa @rica213 
👉🏽 Ambrose @ambrose-kibet 
👉🏽 Frempong @frempongdev 
👉🏽 Shaaibu @shaaibu7 

Here is our Kanban setup : https://github.com/users/rica213/projects/8/views/1

### Below is a screenshot of our board. ⬇️ 
Tasks 1- 8 📸 
![image](https://github.com/rica213/vr-world/assets/117144028/30d066a6-db03-46d2-a4ac-3903cb25639b)

Tasks 9 - 16 📸 
![image](https://github.com/rica213/vr-world/assets/117144028/0c4a0bb7-4f0a-4618-bfd3-bdc2c7e42d5d)

Tasks 17 - 23 📸 
![image](https://github.com/rica213/vr-world/assets/117144028/bb30380a-a09e-4142-9df4-174cff9a081f)

**Comment by Meltrust** [comment]
Hi @rica213,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have been assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

According to the project requirements:

![image](https://github.com/rica213/vr-world/assets/57421823/058b1ae7-7cb3-4a74-8cf2-a1c2d87bf950)

At the time of this review, these are the pointings:

@shaaibu7 27.75
@rica213 24.75
@frempongdev 31.75
@ambrose-kibet 29.75

The requirement is that no team member should have more than 5 points than any other.

As you can see, @rica213 has a lot fewer points than the others (7+).  This is because 31.75 - 24-75 = 7.  7 > 5.  

Therefore:

- [ ] Please ensure no team member has more than 5 points than any other member of the team. 

_tip:  Just play with the numbers and/or reassign some tasks so @rica213 has at least 26.75 points, and you will meet the requirement._

- [ ] I can't see a task to add the API documentation.  This is a requirement for 4 people teams.  Kindly add the task. Please ensure this new task has a description and assignee, and ensure that the pointings are still equal (no more than 5 points than any other member).

## Optional suggestions


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi @rica213,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  
Congratulations! 🎉 

### To highlight

- The kanban board now includes tasks for new reservations and adding items ✔️
- The pointings are now fair, and equal ✔️  


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
